### ISSUE TITLE
Unable to view the test message in the "testbucket" S3 bucket.

### ISSUE THREAD

**Issue by Martin-Biomed** [sborsay/Serverless-IoT-on-AWS#1]
Hi,

I'm having a bit of trouble confirming whether I can send data from my test Lambda function to my S3 bucket on AWS.

I constructed the code as was mentioned in Part 1 of the tutorial: https://www.youtube.com/watch?v=NALTj_ZepNE

![image](https://user-images.githubusercontent.com/50542181/181863892-0c906721-24ce-4e3d-a9a5-86c9b4da6eb6.png)

I'm up to the part where we send out the test payload. From the Lambda console, it appears as though the message was successfully sent: 

![image](https://user-images.githubusercontent.com/50542181/181864038-9d9c0a5d-2017-4b0b-bff6-24b11e17fc1a.png)

I am unable to see any created objects in my S3 bucket though: 

![image](https://user-images.githubusercontent.com/50542181/181864103-b6dceb70-7b4d-4e10-92a5-42e6fc50fe88.png)

Both my Lambda and my S3 bucket are created in the same region. My permissions are also set up for my Lambda function role to have complete S3 access:

![image](https://user-images.githubusercontent.com/50542181/181864152-ab762a4d-a09c-4bd2-8512-3f523d9b1d86.png)

Is the function working fine? Or did something go wrong along the way?

Thanks so much in advance

**Comment by sborsay** [comment]
I Don't see any obvious issues.  You can likely diagnose your issue by going to AWS CloudWatch and looking at the logs for your Lambda function.  It will almost certainly show the error considering your issue.

**Comment by Martin-Biomed** [comment]
Yeah it was fine, no issues. CloudWatch suggestion helped, I just hadn't saved the Lambda (the proper way) in between deployment versions.

**Comment by sborsay** [comment]
Ok great, usually cloudwatch can debug Lambda issues, but in your case it
can be Lambda deployment or S3 security settings issues.
