### ISSUE TITLE
Unable to Update Web Interface with S3 data

### ISSUE THREAD

**Issue by Martin-Biomed** [sborsay/Serverless-IoT-on-AWS#2]
Hi everyone,

I'm having a problem with the last step of this tutorial.

I seem to have followed all the steps in the tutorial, but my website never links to the S3 bucket I allocated for IoT data.  The website never updates from showing "Dashboard", "Line Chart" and "Bar Chart", and I've tried to map out what could have gone wrong.

As far as I can understand, the entire tutorial results in an AWS implementation like what is shown below (my version anyways): 

![image](https://user-images.githubusercontent.com/50542181/198871599-82e1bcb1-2b60-4b9f-b366-e26e147541bd.png)

I've enabled the permissions in both my S3 buckets to be entirely Public (like the tutorial said).

My Lambda function has outputted the data in the correct format. The object URLs in my IoT bucket are of form: https://martin08testbucket.s3.ap-southeast-2.amazonaws.com/testfolder/1667121572339

This is why I also modified the index.html code to include the region, I only made three modifications to the default index.html code and all three mods are shown below:

![image](https://user-images.githubusercontent.com/50542181/198871474-e5ab6826-0fbb-4ba9-ba1a-73151bce0de7.png)

If anyone has an idea as to why my website doesn't display the desired result, it would really help me out.

Thanks again :)

**Comment by sborsay** [comment]
Have you tried the debug window of your browser for error messages in your
code?

Control + Shift + I  or Control + Shift + j

Also watch my S3 bucket settings video on YouTube:
https://www.youtube.com/watch?v=NRroUUR9kdg&t=2s

I would bet one of those methods will fix your issue.

SD B

**Comment by Martin-Biomed** [comment]
Thank you so much.

You were right, that video had a few extra permissions that I needed to enable in my S3 IoT bucket.

**Comment by sborsay** [comment]
Glad to hear it!
