### ISSUE TITLE
S3 data not showing on chart

### ISSUE THREAD

**Issue by eddieo45** [sborsay/Serverless-IoT-on-AWS#6]
hello, 
I am having the same issue that a previous user had in the issues board. MY webpage loads and shows the charts, but my data is not on the chart for some reason. I followed all steps to allow public access and wrote my bucket and folder names correctly. Do you know what could be causing this?

**Comment by sborsay** [comment]
Hi,

I believe the last user solved the issue by rechecking their bucket
settings to ensure the pucket has public access and an open bucket and CORS
policy

**Comment by eddieo45** [comment]
I believe I followed all the correct steps for both of my bucket settings and the policies. I have attached screenshots showing all settings and policies as well as a screenshot of my static webpage to show you that it is displaying charts, but with no data. Could there be an issue in the HTML/js code at all?

![Screenshot (411)](https://user-images.githubusercontent.com/119365238/205759919-ff2b3b9d-3cea-409a-82f3-4f8d815aa618.png)
![Screenshot (412)](https://user-images.githubusercontent.com/119365238/205759934-959cfa4d-fdfa-4f1b-b5ac-8912916df229.png)
![Screenshot (413)](https://user-images.githubusercontent.com/119365238/205759946-5f94e355-0e4f-4fc6-8e55-935e5aad3e9b.png)
![Screenshot (414)](https://user-images.githubusercontent.com/119365238/205759958-c765157e-3417-4c8b-ba81-4e3b18870b77.png)
![Screenshot (415)](https://user-images.githubusercontent.com/119365238/205760397-d59edae4-f9bd-481b-9612-6923e741f237.png)

**Comment by sborsay** [comment]
That warning isn't the issue,

It is likely the settings in your data bucket that are incorrect.  Also
check that your webcode is calling the correct bucket URL

Also you can just move the iot data into the same file in which the web
files are invoked and fetch it directly from there.

**Comment by eddieo45** [comment]
I wanted to attach my code first to see if you notice anything incorrect here but if not I can then just move the iot data into the same bucket as the web page.

![Screenshot (417)](https://user-images.githubusercontent.com/119365238/205779687-23c7718e-7258-416d-b8fa-ce36cfcd1f31.png)

**Comment by sborsay** [comment]
It is odd you are not getting an error  message from your browser console
window, it seems it just can't find the data at that location or there is
no data there.  Is the data at the base level of your bucket?

**Comment by eddieo45** [comment]
The data is in a folder named esp32data, but should i move it into a folder in the same bucket that is hosting the web page??

**Comment by sborsay** [comment]
Try pointing the web code url to the folder/key url that contains the data first

**Comment by eddieo45** [comment]
i believe the web code already has the folder url.

**Comment by sborsay** [comment]
can you send me a picture of your data folder

**Comment by eddieo45** [comment]
This is my data folder that I am trying to show in the chart. Today I created a new folder in the same bucket as the static web hosting but that didnt change anything.

![Screenshot (418)](https://user-images.githubusercontent.com/119365238/205993373-7da9fafc-3153-480d-8b50-9110a7dc9e80.png)

**Comment by eddieo45** [comment]
I am following the code provided in the description of this YouTube video:

https://www.youtube.com/watch?v=vn-H2lhcSko&list=PLGukF1bgpf1MUBX9Yy4i82KcnvUirS9bx&index=17

If you see any errors in the code please let me know

**Comment by eddieo45** [comment]
I believe the issue is with the data arrays in this first screenshot and the data not being placed into them. Because in the second screenshot, I remove the data arrays and add values manually, the chart displays these values.
![Screenshot (419)](https://user-images.githubusercontent.com/119365238/206003884-9ccfc4a2-cc8e-423d-a138-010763aee62e.png)
![Screenshot (420)](https://user-images.githubusercontent.com/119365238/206003913-42765e33-6ab3-42fc-8498-860fdda4576b.png)

**Comment by sborsay** [comment]
I deleted my original code so I have to create a new data bucket, can you open one of the data folders so I can see the exact format of the environmental sensor data?

**Comment by eddieo45** [comment]
this is how the data is formatted:
![Screenshot (421)](https://user-images.githubusercontent.com/119365238/206006057-a955a901-9126-4318-8ca5-0d26c8e3c49a.png)

**Comment by eddieo45** [comment]
would you like  me to attach my entire index.html code that i am using?

**Comment by sborsay** [comment]
ok I will try to solve this today, I just have to recreate the code on some new buckets

**Comment by eddieo45** [comment]
okay thank you please update me when you can

**Comment by sborsay** [comment]
No, i think the issue is how aws is now presenting the url.  I hope to solve it in next 1-3 days.  Hopefully thats enough time for your nyit project.  I need to test some alterations

**Comment by eddieo45** [comment]
wait i came across these errors, how do i fix this issue?
![Screenshot (423)](https://user-images.githubusercontent.com/119365238/206037001-6fea861b-3d00-407a-b1a5-ce897eb1fdc1.png)

**Comment by sborsay** [comment]
CORS shouldn't be an issue if the files are in the same bucket as it is same origin.

You can issue a pull request if you fix it and I will merge the fix in github

**Comment by eddieo45** [comment]
this error is when i am using data from a different bucket

**Comment by sborsay** [comment]
Yes but I'm using the data from the dame bucket and it still isn't parsing data

**Comment by eddieo45** [comment]
I believe I made some sort of error in creation. My partner followed steps and it worked. Thanks for assistance.

**Comment by sborsay** [comment]
I figured out your problem, you made a simple mistake.

'esp32data/'  should be just 'esp32data' the extra backslash messed up the
parse
